export const LOADCATEGORY = "LOAD/CATEGORIES";
export const SETDIFFICULTY = "SET/DIFFICULTY";
export const SETQUESTION = "SET/QUESTION";
export const SETCATEGORY = "SET/CATEGORY";
export const SETNUMBER = "SET/NUMBER";
export const LOADQUESTION = "LOAD/QUESTION";
